### ISSUE TITLE
Non-existent attributes

### ISSUE THREAD

**Issue by Andrej-Kalocanj-Mohaci** [rapw3k/DEMETER#8]
Greetings,

If we need to describe a field (i.e. vehicle breaking) that is non-existent in "https://w3id.org/demeter/agri-context.jsonld", do we add a custom field of it?

Is there an UML model of all classes with their fields, or can we put any class in every class, field like food density in silos is also non-existent but in a class agriProfile exists field Density, can we put an agriProfile with density inside an Building class?

Kind regards

**Comment by rapw3k** [comment]
Hi @Andrej-Kalocanj-Mohaci , to define additional terms you need to create extensions to AIM. You can check existing extensions in extensions folder.
There is no high level UML, as AIM is based on and aligns existing models and extend them as needed. 
The best way to find concepts/types and properties/fields, is either via agroportal or OGC definition server, as described in the README (https://github.com/rapw3k/DEMETER/blob/master/models/README.md). For example you can browse concepts and properties in AIM via http://agroportal.lirmm.fr/ontologies/DEMETER-AIM. However, detailed semantics like domains/ranges contraints of properties (if any), are not shown there. The way of checking this visually is via an ontology editor as described in README too. 
Regards
